exclude: "[.](ipynb)$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-xml
      - id: check-case-conflict
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^migrations/
      - id: trailing-whitespace
        exclude: ^migrations/
      - id: check-added-large-files
        exclude: ^src/xngin/apiserver/testdata/testing_dwh.csv.zst$
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: ed07c6e8889cf83a7245866d1dd007d1f93bf55e  # frozen: 0.9.13
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 36243b70e5ce219623c3503f5afba0f8c96fda55  # frozen: v0.14.7
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  # mdformat plugins are not all compatible with mdformat 1.0.0 yet.
  - repo: https://github.com/hukkin/mdformat
    rev: 83dc2ce5ca115d3390b9b5561d2898366faf0742  # frozen: 0.7.2
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-toc
  - repo: local
    hooks:
      - id: uv-run-mypy
        'types_or': [ python, pyi ]
        args:
          - --config-file=pyproject.toml
          - src
        entry: uv run mypy
        language: system
        name: mypy
        pass_filenames: false
        require_serial: true
      - id: export-openapi-spec
        entry: uv run xngin-cli export-openapi-spec --output /dev/null
        files: ^(?!.*test_).*api\.py$
        language: system
        name: export-openapi-spec check
        pass_filenames: false
        require_serial: true
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 1e30511413f07e516c1844ba91abce8aca984963  # frozen: v1.18.0
    hooks:
      - id: zizmor
